import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js + Electron + SQLite Template",
  description: "Generated by create next app and electron",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <base href="./" />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
